apiVersion: v1
kind: Service
metadata:
  name: wms-backend-service
  labels:
    app: wms-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: wms-backend
