"""Add description to Book

Revision ID: 1605e8cca437
Revises: f2b7ba205465
Create Date: 2026-07-22 12:31:29.233798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1605e8cca437'
down_revision: Union[str, Sequence[str], None] = 'f2b7ba205465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('previous_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('new_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('target_grade', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('primary_reason_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('defect_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('books', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'description')
    op.drop_table('admin_audit_logs')
    # ### end Alembic commands ###
