"""Add Enum for users

Revision ID: 28574981e694
Revises: 1605e8cca437
Create Date: 2026-07-22 12:48:38.030081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28574981e694'
down_revision: Union[str, Sequence[str], None] = '1605e8cca437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE userroleenum AS ENUM ('MASTER', 'ADMIN', 'WORKER', 'GUEST')")
    op.execute("CREATE TYPE userstatusenum AS ENUM ('ACTIVE', 'INACTIVE')")
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userroleenum USING role::userroleenum")
    op.execute("ALTER TABLE users ALTER COLUMN status TYPE userstatusenum USING status::userstatusenum")
    op.execute("ALTER TABLE users ALTER COLUMN status SET DEFAULT 'ACTIVE'::userstatusenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE varchar(20) USING role::text")
    op.execute("ALTER TABLE users ALTER COLUMN status TYPE varchar(20) USING status::text")
    op.execute("DROP TYPE userroleenum")
    op.execute("DROP TYPE userstatusenum")
    # ### end Alembic commands ###
