"""add label_print_jobs queue table

Revision ID: 28eaad3456f0
Revises: 5fa680438753
Create Date: 2026-08-05 04:53:30.850373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28eaad3456f0'
down_revision: Union[str, Sequence[str], None] = '5fa680438753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_print_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lpn', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('zpl', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('printed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_print_jobs_lpn'), 'label_print_jobs', ['lpn'], unique=False)
    op.create_index(op.f('ix_label_print_jobs_status'), 'label_print_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_print_jobs_status'), table_name='label_print_jobs')
    op.drop_index(op.f('ix_label_print_jobs_lpn'), table_name='label_print_jobs')
    op.drop_table('label_print_jobs')
    # ### end Alembic commands ###
