"""baseline: current nexus wms schema

Revision ID: 93914f0eae5a
Revises: 
Create Date: 2026-08-05 03:32:47.304422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93914f0eae5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('published_date', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('category_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('cover_image_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('standard_size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('depth_mm', sa.Float(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('calc_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('virtual_stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_table('fds_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('fraud_score', sa.Integer(), nullable=False),
    sa.Column('fraud_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('rule_code', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbound_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rack', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('shelf', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_barcode'), 'locations', ['barcode'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
    sa.Column('ref_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('target_role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sa.Enum('MASTER', 'ADMIN', 'WORKER', 'GUEST', name='userroleenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatusenum'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_table('weekly_insights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_week', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('saved_labor_cost_krw', sa.Integer(), nullable=False),
    sa.Column('top_defective_publishers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_hotspots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logistics_hotspots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_returns', sa.Integer(), nullable=False),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_insights_report_week'), 'weekly_insights', ['report_week'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('previous_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('new_state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('target_grade', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('primary_reason_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('defect_coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('board_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attachment_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbound_job_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inbound_job_id'], ['inbound_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'location_id', name='uq_inventory_book_loc')
    )
    op.create_table('inventory_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('condition_grade', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('target_lpn', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('picked_location', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('condition_pref', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picking_instructions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('instruction_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('picked_items', sa.Integer(), nullable=False),
    sa.Column('route_summary', sa.Text(), nullable=True),
    sa.Column('worker_note', sa.Text(), nullable=True),
    sa.Column('ai_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('accepted_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('box_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('cushion_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('cj_waybill_no', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('packed_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picking_instructions_instruction_no'), 'picking_instructions', ['instruction_no'], unique=True)
    op.create_index(op.f('ix_picking_instructions_order_id'), 'picking_instructions', ['order_id'], unique=False)
    op.create_table('return_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ubci_score', sa.Integer(), nullable=True),
    sa.Column('agent_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('ticket_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['return_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_used_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('lpn_barcode', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ubci_score', sa.Integer(), nullable=True),
    sa.Column('condition_grade', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('certificate_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('item_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('source_job_id', sa.Uuid(), nullable=True),
    sa.Column('inspection_source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('inspected_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('inspected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_job_id'], ['return_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_used_items_lpn_barcode'), 'inventory_used_items', ['lpn_barcode'], unique=True)
    op.create_table('order_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_job_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('reject_reason_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('sales_velocity_30d', sa.Integer(), nullable=False),
    sa.Column('rejected_quantity', sa.Integer(), nullable=False),
    sa.Column('baseline_quantity', sa.Integer(), nullable=False),
    sa.Column('proposed_quantity', sa.Integer(), nullable=False),
    sa.Column('urgency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('ai_source', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('decided_by', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_job_id'], ['return_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_proposals_book_id'), 'order_proposals', ['book_id'], unique=False)
    op.create_index(op.f('ix_order_proposals_status'), 'order_proposals', ['status'], unique=False)
    op.create_table('picking_instruction_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instruction_id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=True),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('used_item_id', sa.Uuid(), nullable=True),
    sa.Column('stock_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('lpn_barcode', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('picked_quantity', sa.Integer(), nullable=False),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('rack', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('shelf', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('pick_seq', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.Column('picked_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instruction_id'], ['picking_instructions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_item_id'], ['inventory_used_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picking_instruction_items_instruction_id'), 'picking_instruction_items', ['instruction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picking_instruction_items_instruction_id'), table_name='picking_instruction_items')
    op.drop_table('picking_instruction_items')
    op.drop_index(op.f('ix_order_proposals_status'), table_name='order_proposals')
    op.drop_index(op.f('ix_order_proposals_book_id'), table_name='order_proposals')
    op.drop_table('order_proposals')
    op.drop_index(op.f('ix_inventory_used_items_lpn_barcode'), table_name='inventory_used_items')
    op.drop_table('inventory_used_items')
    op.drop_table('boards')
    op.drop_table('return_jobs')
    op.drop_index(op.f('ix_picking_instructions_order_id'), table_name='picking_instructions')
    op.drop_index(op.f('ix_picking_instructions_instruction_no'), table_name='picking_instructions')
    op.drop_table('picking_instructions')
    op.drop_table('order_items')
    op.drop_table('inventory_logs')
    op.drop_table('inventory')
    op.drop_table('inbound_items')
    op.drop_table('board_posts')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_weekly_insights_report_week'), table_name='weekly_insights')
    op.drop_table('weekly_insights')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('orders')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_locations_barcode'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('inbound_jobs')
    op.drop_table('fds_reports')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
