"""init_wms_core_schema

Revision ID: d1ff6db7e3b3
Revises: 
Create Date: 2026-07-13 17:40:54.126911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1ff6db7e3b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('inventory_used_items', sa.Column('item_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('inventory_used_items', sa.Column('source_job_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'inventory_used_items', 'return_jobs', ['source_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_used_items', type_='foreignkey')
    op.drop_column('inventory_used_items', 'source_job_id')
    op.drop_column('inventory_used_items', 'item_status')
    op.drop_column('books', 'is_active')
    # ### end Alembic commands ###
