"""add_sci_metrics

Revision ID: d316eb0afea5
Revises: d1ff6db7e3b3
Create Date: 2026-07-13 20:03:30.974560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd316eb0afea5'
down_revision: Union[str, Sequence[str], None] = 'd1ff6db7e3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_jobs', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('return_jobs', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_jobs', 'retry_count')
    op.drop_column('return_jobs', 'latency_ms')
    # ### end Alembic commands ###
